[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate --settings=fashion_backend.production && python manage.py collectstatic --noinput --settings=fashion_backend.production && gunicorn fashion_backend.wsgi --settings=fashion_backend.production"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
