# Generated by Django 5.2.6 on 2025-09-28 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('view_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FashionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fashion_images.teammember')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
