# Generated by Django 5.2.6 on 2025-09-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_images', '0002_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Supabase URL for the image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='file_url',
            field=models.URLField(blank=True, help_text='Supabase URL for the media file', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fashionimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
